### PR TITLE
Use standard java equals and hash code for performance

### LINKED ISSUE #15: Standardlise hashCode and equals for performance
Hi,
I have been a user of jbool_expressions for a while and have found it very good.

I was wondering if you would consider a pull request to implement hashCode and equals using standard java patterns rather than using string manipulation? 

The reason for this is that I noticed during profiling that all this string manipulation shows up as a hot method.

The changes are pretty simple:

1. remove hashCode and equals from Expression.
2. change Expression#compareTo to compare via hashCode rather than string.
3. implement hashCode and Equals in subclasses of Expression.

The downside of this is that this is a breaking change. Users with custom Expressions will have to implement hashCode and equals on all their subclasses of Expression.

The upside is that string manipulation is eliminated and implementing hashCode and equals can be optimised on a class by class basis.

### PR DESCRIPTION
**Pull request by BrynCooke**
Fixes #15

Sorry for the spam. I've changed the branch name for merging in.

For ease of development I upgraded to java 7 and bumped junit. This could be reverted to 1.6.

Equals and hash code implementations were mostly generated using the standard generator in IntelliJ
As expressions are no longer sorted lexicographically the test results have also changed in order. They look the same though.

### CODE REVIEW

**Comment by bpodgursky** [comment]
Thanks @BrynCooke!  I will take a look at this -- might take me a day or two.

**Comment by bpodgursky** [comment]
I think this makes sense and I don't see any obvious correctness bugs. 

I think bumping to Java 7 is fine.  If there are complaints from users after merging, I'll probably convert back to Java 6, but it seems unlikely these days.

Do you have any especially bad expressions I can use as a before / after sanity-check performance test?  I can find some from previous issues here if you don't have them offhand.  Probably not a bad idea to have a test suite for performance changes in the future...

Re: sorting.  From a correctness standpoint, the sorting is only necessary so that simplification ends when the expression is stable, and being unsorted could make that loop forever.  That said, I think there is value in lexicographic ordering for human debugging and output. I was thinking maybe:

- RuleSet.simplify could simplify/convert using the logic defined here, but before returning the simplified result, it does a final pass which applies a lexicographic sort.  (hopefully this will be trivial cost compared to the comparisons during simplification) 

- a new method RuleSet.fastSimplify (or something similar) would be available which skips the final lexicographic sort (for programmatic uses which don't care about order).

Do you think that makes sense and still address the performance problems you saw?

The last suggestion is a bit fiddly, so if you don't have time to take a look at it, I can do it this weekend.

Thanks again for the PR!

**Comment by BrynCooke** [comment]
Yeah, moving the lexicographic sort out to a rule sounds like a nice idea.

Regarding perf tests I created something locally that represents the sort of thing I am doing :
https://gist.github.com/BrynCooke/875d1283b99255b45e08598f9b10a7d7

When running against the current master the results settle on around 1000ms whereas the new PR settles at around 800ms.

In addition I did some performance testing using visualVM and found that heap usage by the new PR was much better. The heap never got above 100mb vs regularly peaking at 400mb on master.

If I remove the caching of toString in complex then then things get worse on master with heap peaking at 1gb and results of 1200ms. I think with the PR is it probably safe to remove the existing caching.

So the PR is only a modest perf boost, but a fairly big win for heap usage.

All this being said it is clear from visualVM that the most time is spent in SimplifyNExprChildren I don't immediately see how this can be improved though.... At some point I may get a chance to revisit this area.

**Comment by bpodgursky** [comment]
I put together a fairly naiive benchmarking script and tested this out on 10,000 randomly generated expressions here: https://github.com/bpodgursky/jbool_expressions/commit/d8a9611265d372c48d09a6c25a18dbb027a6de9f

results:

---- current master
Total parse time:	2194
Total simplify time:	3464
Total sop time:	22785
Total pos time:	46202

---- this PR

Total parse time:	1726
Total simplify time:	3448
Total sop time:	17011
Total pos time:	29572

So I think there are non-trivial speed improvements (at least on the fairly dumb test data I generated). 

I will take a look this weekend at adding the lexicographic sort (if you haven't done it already) and merge.

**Comment by BrynCooke** [comment]
I didn't get time to do the lexicographic sort, but there is a reasonable chance that I'll be able to submit further PRs around performance in future.
Thanks for looking at this!

**Pull request merged**
