### PR TITLE
Improve RuleSet#toDNF performance

### PR DESCRIPTION
**Pull request by imaronna**
This PR improves the performance of the `.toDnf` function. 

While before it applied the `DeMorgan` rules to the raw Expression, this PR first simplifies the expression and then applies the `DeMorgan` rules.

This has improved performance significantly. Various expressions which took ~1min30sec to parse now take ~5 seconds.

### CODE REVIEW

**Comment by bpodgursky** [comment]
Thanks!  Do you need a release to pick this up?

**Comment by bpodgursky** [comment]
Done, should be in central in a few hours.

**Comment by bpodgursky** [comment]
Done, should be in central in a few hours.

**Comment by imaronna** [comment]
tyvm!

**Pull request merged**
