### PR TITLE
remove unnecessary dependencies and add version tags in pom

### PR DESCRIPTION
**Pull request by AlbertGevorgyan**
Dear Ben Podgursky

I really like jbool_expressions but would suggest to eliminate dependencies on guava and commons libraries. This pull request is based on a branch written by my colleague, Ludovic Orban, which is Java 7 compatible. Next I am going to submit another pull request with Java 8 code replacing Optionals and StringUtils. Would appreciate if you merge either of these requests - whichever you prefer.

Many thanks
Albert Gevorgyan

### CODE REVIEW

**Comment by bpodgursky** [comment]
Thanks for the PRs.  Sorry for the slow replies, but it will take me a few days to get around to reviewing these -- not forgotten though.

**Comment by AlbertGevorgyan** [comment]
Thank you!

**Comment by AlbertGevorgyan** [comment]
Dear Ben Podgursky

At Terracotta team we are currently exploring the possibility of using your library in one of our products. 
Could you please let me know if you had a chance to look at the PR? If you don't have time or do no wish to accept the changes, we can create and maintain a fork.

Many thanks
Albert

**Comment by bpodgursky** [comment]
Sorry, I got really busy, and I left this slip.  I had a started to put together my thoughts, and I will finish that later tonight, but my initial thoughts are

- I agree that bumping to Java 8 is a good idea.  
- specifying plugin versions is a good idea
- switch the antlr dependency to antlr-runtime is probably a good idea

I think what I disagree on is removing the dependencies in favor of copy paste.  I agree that dependency bloat is bad, but Guava and commons-lang are really standard libraries.  

I'm happy to push those first three changes.  I think I would lean against the dependency removal though, unless there's a really strong argument for why these dependencies introduce conflicts (alternatively, I'm happy to update the versions, if that is the problem).

**Comment by AlbertGevorgyan** [comment]
Thanks for agreeing to push the changes. Upgrading the versions may be helpful too - I will let you know later if we need it or will submit another PR.

**Comment by bpodgursky** [comment]
I have pushed https://github.com/bpodgursky/jbool_expressions/pull/25/files with the changes that don't remove the dependencies.  I'm happy to update any of the deps if necessary.  Let me know if you think that would be helpful, or I will perform a release as-is sometime in the next couple days.

**Comment by lorban** [comment]
Ben,
(FYI, I'm a colleague of @AlbertGevorgyan)

There are two reasons why we would like to get rid of the jbool_expressions dependencies:
 1) They can easily be replaced with equivalents already present in the JDK.
 2) We find it sad and inconvenient to have to add over two megabytes of dependencies and potentially complicate a users' dependency graph (like in our case, were we use conflicting versions of the same libs) for things that the JDK provides out of the box.

jbool_expressions has three dependencies that we carefully analyzed: commons-lang 2.5, commons-lang3 3.6 and guava 14.0-rc3.

Regarding commons-lang3: it's not used at all so we believe it can just be taken out.

Regarding commons-lang 2.5:

 - It is used in the toString() method of the And and Or classes. We originally duplicated the commons-lang StringUtils.join() method to stick to the JDK 1.7 API, but since you agreed to upgrade to 1.8 those can easily be replaced with java.lang.String.join() calls instead, using a little bit of streams magic to convert the array of Expression into an array of String.
 - The same StringUtils.join() method is also used in the GenerateExpressionExamples class and can also be replaced with String.join().

Regarding guava:

 - You mostly used Guava for the Lists.newArrayList(), Lists.newLinkedList() and Maps.newHashMap() helpers that can trivially be replaced by new ArrayList(), new LinkedList() and new HashMap() constructor calls instead.
 - The only other usage of Guava you made was the use of HashMultimap. Again, this can easily be replaced with a a HashMap<K, Set<V>> at the expense of merely an extra line of code.

I've submitted a PR with those changes applied on top of your current master to show you the differences over here: https://github.com/bpodgursky/jbool_expressions/pull/26

We'd be thrilled if you could reconsider this change.
Many thanks!

**Comment by bpodgursky** [comment]
Ok, fair enough.  I agree that the Java 8 syntax improvements eliminate a lot of the gain from Guava.  If this made heavier use of Multimaps it would be annoying, but it's only the one.   I'm good merging #26 as-is.

Sorry for the super slow response on these suggestions.  I'll do a release today with these changes.

**Comment by bpodgursky** [comment]
These changes were released in v1.15 (other PR was merged).  Should be in maven central.  Thanks again for the changes, and sorry for the slow turnaround!

**Pull request closed without merging**
