### PR TITLE
Add rule for DistributiveLaw

### PR DESCRIPTION
**Pull request by nulls**
Hi,

The project [saveourtool/diktat](https://github.com/saveourtool/diktat) (static analysis library for kotlin) uses your library to simplify boolean expressions.
We supported DistributeLaw as jbool.Rule in our project in scope of https://github.com/saveourtool/diktat/pull/1369

We would like to contribute it to your project. 
Can you please look at this PR and suggest what's items need to be done

Thanks!

### CODE REVIEW

**Review by bpodgursky — APPROVED** [review]
This is cool, thanks for putting this together.

I think if we wanted get this added to the list of default simplification rules I'd need to do some aggressive testing to make sure we don't end up in infinite cycles in edge cases (I've accidentally done this before).  But as a standalone rule I have no concerns.

Do you want me to do a point release to pull this in?  I should be able to do that tonight if helpful.

**Comment by nulls** [comment]
> Do you want me to do a point release to pull this in? I should be able to do that tonight if helpful.

It will be great, thanks

**Comment by akuleshov7** [comment]
I think that there is no need to rush with the release now, but will be great to have it released in some time

**Comment by nulls** [comment]
Hi @bpodgursky,

I see that https://github.com/bpodgursky/jbool_expressions/releases/tag/1.24 was cut, but I can't find this version in Maven Central: https://mvnrepository.com/artifact/com.bpodgursky/jbool_expressions.

Is it possible to deploy it?

Thanks!

**Comment by bpodgursky** [comment]
Sorry about the delay here.  The headache is that I set this release up as a Travis workflow, and then Travis discontinued their OSS support, and I need to get it moved over to github actions (and figure out how to retrieve the secrets).  Will take a look at that over the next week.

**Comment by akuleshov7** [comment]
> Sorry about the delay here. The headache is that I set this release up as a Travis workflow, and then Travis discontinued their OSS support, and I need to get it moved over to github actions (and figure out how to retrieve the secrets). Will take a look at that over the next week.

@nulls can help you with migration to Actions. It is awesome

**Comment by bpodgursky** [comment]
Yeah I use it for work so I'm not too worried.  I'm having trouble finding the gpg key I used for travis, so hopefully maven central won't whine too much if I generate a new one.

**Comment by akuleshov7** [comment]
> Yeah I use it for work so I'm not too worried. I'm having trouble finding the gpg key I used for travis, so hopefully maven central won't whine too much if I generate a new one.

Yeah, we generated new several times. No problems from central

**Comment by bpodgursky** [comment]
Alright that was a lot of fun, but I think I probably successfully just published 1.23 to central.  Let me know if you see anything wrong with the release.

**Comment by nulls** [comment]
@bpodgursky, version [`1.23`](https://repo1.maven.org/maven2/com/bpodgursky/jbool_expressions/1.23/) is old version which already is on maven central.
but I see a new version is uploaded: [jbool_expressions-1.23](https://repo1.maven.org/maven2/com/bpodgursky/jbool_expressions/jbool_expressions-1.23/)

Looks like version is passed as `jbool_expressions-1.23` instead of `1.23`. And I think it should be `1.24`

**Comment by bpodgursky** [comment]
Ok.  One more try?

**Comment by nulls** [comment]
Thanks a lot! Now I see [`1.24`](https://repo1.maven.org/maven2/com/bpodgursky/jbool_expressions/1.24/)

**Pull request merged**
